name: Build

on:
  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'

jobs:
  build:
    name: Build Bionames
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install git+https://github.com/pyobo/pyobo.git
      - name: PyOBO Version
        run: pyobo --version
      - name: Build
        run: pyobo database names --no-strict
